# Generated by Django 3.1.4 on 2021-02-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['-status_sort_order']},
        ),
        migrations.AddField(
            model_name='status',
            name='status_sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
