# Generated by Django 3.1.4 on 2021-02-02 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210202_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['status_sort_order']},
        ),
        migrations.AddField(
            model_name='job',
            name='approver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.approver'),
        ),
    ]
