# Generated by Django 3.1.4 on 2021-02-04 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210202_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-pk']},
        ),
    ]
