# Generated by Django 3.1.4 on 2021-02-05 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtype_name', models.CharField(max_length=120)),
                ('jobtype_descrip', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='jobcard_number',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.jobtype'),
        ),
    ]
