# Generated by Django 3.1.4 on 2021-02-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_job_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contractor_group',
            field=models.CharField(choices=[[4, 'Unitrans - Landprep'], [5, 'MCP - Field Services'], [6, 'MCP - Civils'], [7, 'Unitrans - Roads']], default=4, max_length=200),
        ),
    ]
